version: '3.7'

services:
  app:
    build: .
    env_file:
      - .env
    ports: 
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
      - postgres
  
  mongo:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mongo:
  postgres: